Repository codervivek5/VigyBag, pull requests merged in 2023-10, with the labels that each got.

#864 Fix size and overflow
  index.html
  script.js
  style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#871 made our services section perfectly responsive
  index.html
  style.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#882 Make Footer Responsive.
  index.html
  style.css
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted

#874 Our service section updated
  index.html
  style.css
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted

#876 Footer Updated
  index.html
  style.css
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted

#881 Add environment variables for settings.py
  Backend Code/VigyBag/.gitignore
  Backend Code/VigyBag/VigyBag/settings.py
  Backend Code/VigyBag/requirements.txt
Labels: BackEnd, hacktoberfest, hacktoberfest-accepted

#901 modified login page as per the figma design
  Pages/login/login.css
  Pages/login/login.html
  Pages/login/svg-1.png
  img/Google.png
  img/dial.png
  img/login_logo.png
  img/slide.png
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#896 Added pre-commit hook with Husky, Lint Staged, and Prettier
  .eslintrc.js
  .gitignore
  .husky/pre-commit
  .lintstagedrc.json
  .prettierrc
  package-lock.json
  package.json
  style.css
Labels: hacktoberfest
