Repository codervivek5/VigyBag, pull requests merged in 2023-08, with the labels that each got.

#707 Contact US Page modified
  Pages/contact/contact.css
  Pages/contact/contact.html
Labels: bug, good first issue, level2, gssoc23, FrontEnd

#715 fixed about us brand logo link
  Pages/About Page/about.html
  Pages/contact/contact.html
Labels: bug, good first issue, level2, gssoc23, FrontEnd

#729 Upgraded Code for Product Pop Up Section
  index.html
  style.css
Labels: good first issue, level3, gssoc23, FrontEnd

#717 Enhanced cart page
  Cart/cart.css
  cart/css/style.css
  cart/js/main.js
  style.css
Labels: bug, good first issue, level2, gssoc23, FrontEnd

#726 Modify the navbar
  style.css
Labels: bug, good first issue, level2, gssoc23, FrontEnd

#749 Sign In Page
  Backend Code/VigyBag/db.sqlite3
  Backend Code/VigyBag/templates/account/login.html
  Backend Code/VigyBag/templates/account/signup.html
Labels: good first issue, level3, gssoc23, FrontEnd

#759 Added Search functionality [Home-Page & SeeMore Page]
  Pages/contact/contact.html
  Pages/login/login.css
  index.html
  script.js
  see_more/cart/main.js
  see_more/cart/util.js
  see_more/script.js
  see_more/see_more.html
  see_more/trolley.png
  style.css
Labels: good first issue, level3, gssoc23, FrontEnd

#756 Added Toast Notifications and Fixed Relative URL Paths in Redirects
  Pages/login/login.html
  Pages/login/login.js
  greet.html
Labels: bug, good first issue, level2, FrontEnd

#752 Major Push - SyedImtiyaz-1 {Darkmode, login, showmore-page}
  style.css
Labels: bug, good first issue, level3, gssoc23, FrontEnd

#760 Adding Other Issue Template for Creating Issue Templates
  .github/ISSUES_TEMPLATE/Other.yml
  .github/pull_request_template.md
Labels: bug, good first issue, level2, gssoc23, FrontEnd

#765 Redesign the new testimonial
  Pages/review/review.css
  Pages/review/review.js
  index.html
  style.css
Labels: bug, good first issue, level3, gssoc23, FrontEnd

#777 All New POP UP
  index.html
  script.js
  style.css
Labels: bug, good first issue, level3, gssoc23, FrontEnd

#754 fixed typo error
  index.html
  see_more/see_more.html
Labels: bug, good first issue, level1, gssoc23, FrontEnd

#716 added footer and navbar in login page
  Pages/About Page/about.html
  Pages/contact/contact.html
  Pages/login/login.css
  Pages/login/login.html
  index.html
  script.js
  style.css
Labels: bug, good first issue, level3, gssoc23, FrontEnd

#770 New Back To Top
  index.html
  script.js
  style.css
Labels: good first issue, level3, gssoc23, FrontEnd

#783 Logout Page
  Backend Code/VigyBag/VigyBag/__pycache__/settings.cpython-311.pyc
  Backend Code/VigyBag/VigyBag/__pycache__/urls.cpython-311.pyc
  Backend Code/VigyBag/VigyBag/settings.py
  Backend Code/VigyBag/VigyBag/urls.py
  Backend Code/VigyBag/db.sqlite3
  Backend Code/VigyBag/static/products/Headphones-VigyBag.webp
  Backend Code/VigyBag/templates/account/logout.html
  Backend Code/VigyBag/templates/base.html
  Backend Code/VigyBag/templates/base2.html
  Backend Code/VigyBag/templates/home.html
  Backend Code/VigyBag/templates/product.html
Labels: good first issue, level3, gssoc23, FrontEnd, BackEnd

#787 New Go to top button
  index.html
  script.js
  style.css
Labels: bug, good first issue, level3, gssoc23, FrontEnd

#791 Backend and Frontend Changes Of Product Page
  Backend Code/VigyBag/Product/admin.py
  Backend Code/VigyBag/Product/migrations/0002_color_size_rename_price_product_sellingprice_and_more.py
  Backend Code/VigyBag/Product/models.py
  Backend Code/VigyBag/Product/urls.py
  Backend Code/VigyBag/Product/views.py
  Backend Code/VigyBag/VigyBag/__pycache__/__init__.cpython-311.pyc
  Backend Code/VigyBag/VigyBag/__pycache__/settings.cpython-311.pyc
  Backend Code/VigyBag/VigyBag/__pycache__/urls.cpython-311.pyc
  Backend Code/VigyBag/VigyBag/__pycache__/wsgi.cpython-311.pyc
  Backend Code/VigyBag/VigyBag/urls.py
  Backend Code/VigyBag/db.sqlite3
  Backend Code/VigyBag/media/products/Screenshot_1.png
  Backend Code/VigyBag/templates/account/logout.html
  Backend Code/VigyBag/templates/base.html
  Backend Code/VigyBag/templates/base2.html
  Backend Code/VigyBag/templates/home.html
  Backend Code/VigyBag/templates/product.html
Labels: good first issue, level3, gssoc23, BackEnd

#742 Issue650: Responsive Website
  Pages/review/review.css
  index.html
  style.css
Labels: bug, good first issue, level3, gssoc23, FrontEnd

#798 New Contact Us Page
  Pages/contact/contact.css
  Pages/contact/contact.html
Labels: bug, enhancement, good first issue, level3, gssoc23, FrontEnd

#799 Retrive info from backend
  Backend Code/VigyBag/Product/migrations/0003_product_info_product_seller.py
  Backend Code/VigyBag/Product/migrations/0004_alter_product_rating.py
  Backend Code/VigyBag/Product/models.py
  Backend Code/VigyBag/Product/views.py
  Backend Code/VigyBag/VigyBag/__pycache__/settings.cpython-311.pyc
  Backend Code/VigyBag/VigyBag/settings.py
  Backend Code/VigyBag/db.sqlite3
  Backend Code/VigyBag/static/products/Headphones-VigyBag.webp
  Backend Code/VigyBag/templates/product.html
Labels: good first issue, level3, gssoc23, FrontEnd, BackEnd

#741 Bug report #724 resolved
  index.html
  script.js
  tempCodeRunnerFile.js
Labels: good first issue, level3, gssoc23

#804 Added All the contributors
  .vscode/settings.json
  Pages/Team/team.js
Labels: enhancement, good first issue, level3, gssoc23, FrontEnd

#812 Redesign Contact page
  Pages/contact/contact.css
  Pages/contact/contact.html
  Pages/contact/contact.js
Labels: bug, enhancement, good first issue, level3, gssoc23, FrontEnd

#806 Color options for Product
  Backend Code/VigyBag/Product/migrations/0005_color_image.py
  Backend Code/VigyBag/Product/models.py
  Backend Code/VigyBag/Product/views.py
  Backend Code/VigyBag/VigyBag/__pycache__/settings.cpython-311.pyc
  Backend Code/VigyBag/VigyBag/settings.py
  Backend Code/VigyBag/db.sqlite3
  Backend Code/VigyBag/media/color_images/Headphones-VigyBag.webp
  Backend Code/VigyBag/media/color_images/Screenshot_128.png
  Backend Code/VigyBag/media/color_images/Screenshot_129.png
  Backend Code/VigyBag/media/color_images/Screenshot_130.png
  Backend Code/VigyBag/templates/product.html
Labels: bug, good first issue, level3, gssoc23, FrontEnd

#814 Landing page and dark mode issue resolved
  index.html
Labels: bug, good first issue, level2, gssoc23, FrontEnd

#817 Fixed the website
  index.html
Labels: bug, enhancement, level3, FrontEnd

#819 Product Page Finalized
  Backend Code/VigyBag/templates/base2.html
  Backend Code/VigyBag/templates/product.html
Labels: good first issue, level3, gssoc23, BackEnd

#815 Major Alignment Issue fixed : {no functionality removed}
  .vscode/settings.json
  Backend Code/VigyBag/VigyBag/templates/account/login.html
  Backend Code/VigyBag/VigyBag/templates/account/signup.html
  Pages/Team/team.css
  Pages/Team/team.html
  Pages/review/review.css
  index.html
  script.js
  see_more/script.js
  see_more/see_more.html
  style.css
Labels: bug, good first issue, level3, gssoc23, FrontEnd

#822 Product Details Section
  Backend Code/VigyBag/Product/migrations/0006_product_features_product_speciality.py
  Backend Code/VigyBag/Product/migrations/0007_rename_speciality_product_specifiactions.py
  Backend Code/VigyBag/Product/migrations/0008_alter_product_features_alter_product_specifiactions.py
  Backend Code/VigyBag/Product/models.py
  Backend Code/VigyBag/VigyBag/__pycache__/settings.cpython-311.pyc
  Backend Code/VigyBag/VigyBag/settings.py
  Backend Code/VigyBag/db.sqlite3
  Backend Code/VigyBag/templates/product.html
Labels: good first issue, level3, gssoc23, BackEnd

#820 dark mode color updated
  style.css
Labels: bug, good first issue, level2, gssoc23, FrontEnd

#825 Scroll To Top {Invisible Ready}
  index.html
Labels: bug, good first issue, level2, gssoc23
