Repository codervivek5/VigyBag, pull requests merged in 2023-05, with the labels that each got.

#16 Added hover effect to footer text and social icons
  style/style.css
Labels: good first issue, Easy, GSSOC'23

#22 added effects to the fashion and accessories section
  index.html
  style/style.css
Labels: good first issue, Easy, GSSOC'23

#36 Update style.css and Add space around search bar
  style/style.css
Labels: good first issue, Easy, GSSOC'23

#39 Made the website usable for phone
  img/deviceframes (1) 1(mod).png
  img/deviceframes 1(mod).png
  index.html
  style/style.css
Labels: good first issue, level2, gssoc23

#96 Update index.html Resolve Issue No. #89
  index.html
  style/style.css
Labels: good first issue, level1, gssoc23

#116 [FEATURE] added badges to the product cards
  index.html
  style/style.css
Labels: good first issue, level1, gssoc23

#132 [CHANGE] Hover effect and fixed the template issues
  .github/ISSUE_TEMPLATE/feature_request.md
  .vscode/settings.json
  img/deviceframes (1) 1(mod).png
  img/deviceframes 1(mod).png
  index.html
  style/style.css
Labels: good first issue, level1, gssoc23

#177 #157 Nav Header is Fixed
  index.html
  style/style.css
Labels: good first issue, level1, gssoc23

#175 Add social media links in the footer section Issue #142
  index.html
Labels: good first issue, level1, gssoc23

#182 Language Feature
  img/languageIcon.png
  index.html
  package-lock.json
  style/style.css
Labels: good first issue, level1, gssoc23

#176 Add Hover Effect to Wishlist Icon of Product Card # 162
  index.html
  style/style.css
Labels: good first issue, level1, gssoc23

#178 Home Button Working
  index.html
Labels: good first issue, level1, gssoc23

#214 login page #issue 18 (with fix in prior merge conflict)
  .hintrc
  img/Google.png
  img/Minimalist Happy Shopping Logo (3) 1.png
  img/cross line.png
  img/half-Rectangle.png
  img/svg-1.png
  login.html
  style/login.css
Labels: good first issue, level1, gssoc23

#45 Added favicon issue #44
  index.html
Labels: good first issue, level1, gssoc23

#219 Fix Image Overlapping and Improve User Experience
  img/combined-frames.png
  index.html
  style/style.css
Labels: good first issue, level1, gssoc23

#222 Fixed in Bug in Issue #168
  index.html
  package-lock.json
Labels: good first issue, level1, gssoc23

#227 Container of Headphones and T-shirt is Fixed
  index.html
  style/style.css
Labels: good first issue, level1, gssoc23

#237 Added Clickable Copyright
  index.html
  script.js
  style/style.css
Labels: good first issue, level1, gssoc23

#232 Added png design
  Payment Design/Design 1.png
  Payment Design/Design 2.png
Labels: good first issue, level2, gssoc23

#250 #218 Making a django app within the Django project
  Cart.html
  Payment Design/Design 1.png
  Payment Design/Design 2.png
  img/combined-frames.png
  img/pexels-tim-douglas-6567607.jpg
  index.html
  login/index.html
  login/script.js
  login/style.css
  script.js
  style/cart.css
  style/style.css
Labels: good first issue, level2, gssoc23

#115 Item section updated.
  index.html
  style/style.css
Labels: good first issue, level1, gssoc23

#264 Responsive drop down navbar added
  index.html
  style/style.css
Labels: bug, good first issue, level1, gssoc23

#262 fixed container in the home page
  index.html
  style/style.css
Labels: good first issue, level1, gssoc23, FrontEnd

#288 `Navbar` Bug Fixed
  index.html
  style/style.css
Labels: enhancement, good first issue, level1, gssoc23
