Repository codervivek5/VigyBag, pull requests merged in 2023-06, with the labels that each got.

#333 Linting Fix: comment removed
  style/style.css
Labels: good first issue, level1, gssoc23

#379 new feature for chatbot
  chatBot/script.js
Labels: good first issue, level1, gssoc23, FrontEnd

#339 changed search bar color and font
  style/style.css
Labels: good first issue, level1, gssoc23, FrontEnd

#242 Update README.md
  README.md
Labels: good first issue, level1, gssoc23

#270 Updated Homepage Text Alignment
  style/style.css
Labels: good first issue, level1, gssoc23, FrontEnd

#376 #70 Login Section in VigyBag Android
  Android/.idea/gradle.xml
  Android/.idea/inspectionProfiles/Project_Default.xml
  Android/.idea/misc.xml
  Android/app/build.gradle
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/java/com/vigbag/android/MainActivity.kt
  Android/app/src/main/java/com/vigbag/android/SignInFragment.kt
  Android/app/src/main/java/com/vigbag/android/SignUpFragment.kt
  Android/app/src/main/java/com/vigbag/android/ui/theme/Theme.kt
  Android/app/src/main/res/drawable/splash_image.xml
  Android/app/src/main/res/drawable/vigylogo.png
  Android/app/src/main/res/drawable/vigylogo_small.png
  Android/app/src/main/res/layout/activity_main.xml
  Android/app/src/main/res/layout/fragment_sign_in.xml
  Android/app/src/main/res/layout/fragment_sign_up.xml
  Android/app/src/main/res/values/colors.xml
  Android/app/src/main/res/values/strings.xml
  Android/app/src/main/res/values/themes.xml
Labels: level3, gssoc23, android

#402 updated login form
  .vscode/settings.json
  login/style.css
Labels: enhancement, good first issue, level1, gssoc23, FrontEnd

#404 updated js feature in index.html
  index.html
Labels: good first issue, level1, gssoc23, FrontEnd

#432 Footer Icons are Fixed
  contact/index.html
  index.html
  style/style.css
Labels: good first issue, level1, gssoc23, FrontEnd

#357 FAQ section created
  index.html
  style/style.css
Labels: good first issue, level2, gssoc23, FrontEnd

#440 All Bug Fixed
  contact/index.html
  index.html
Labels: bug, enhancement, good first issue, level1, gssoc23, FrontEnd

#446 Issue template Added
  .github/ISSUES_TEMPLATE/bug.yml
  .github/ISSUES_TEMPLATE/documentation.yml
  .github/ISSUES_TEMPLATE/feature.yml
  index.html
  script.js
  style/style.css
Labels: good first issue, level1, gssoc23

#246 Authentication routes on dev
  Backend Code/VigyBag/VigyBag/__pycache__/__init__.cpython-310.pyc
  Backend Code/VigyBag/VigyBag/__pycache__/settings.cpython-310.pyc
  Backend Code/VigyBag/VigyBag/__pycache__/urls.cpython-310.pyc
  Backend Code/VigyBag/VigyBag/__pycache__/wsgi.cpython-310.pyc
  Backend Code/VigyBag/VigyBag/settings.py
  Backend Code/VigyBag/VigyBag/urls.py
  Backend Code/VigyBag/db.sqlite3
  Backend Code/VigyBag/requirements.txt
  Backend Code/VigyBag/users/__init__.py
  Backend Code/VigyBag/users/__pycache__/__init__.cpython-310.pyc
  Backend Code/VigyBag/users/__pycache__/admin.cpython-310.pyc
  Backend Code/VigyBag/users/__pycache__/apps.cpython-310.pyc
  Backend Code/VigyBag/users/__pycache__/models.cpython-310.pyc
  Backend Code/VigyBag/users/__pycache__/serializers.cpython-310.pyc
  Backend Code/VigyBag/users/__pycache__/urls.cpython-310.pyc
  Backend Code/VigyBag/users/__pycache__/views.cpython-310.pyc
  Backend Code/VigyBag/users/admin.py
  Backend Code/VigyBag/users/apps.py
  Backend Code/VigyBag/users/migrations/0001_initial.py
  Backend Code/VigyBag/users/migrations/__init__.py
  Backend Code/VigyBag/users/migrations/__pycache__/0001_initial.cpython-310.pyc
  Backend Code/VigyBag/users/migrations/__pycache__/__init__.cpython-310.pyc
  Backend Code/VigyBag/users/models.py
  Backend Code/VigyBag/users/serializers.py
  Backend Code/VigyBag/users/tests.py
  Backend Code/VigyBag/users/urls.py
  Backend Code/VigyBag/users/views.py
Labels: good first issue, level2, gssoc23, BackEnd

#459 fixed DarkMode Icon margin Bug
  style/style.css
Labels: good first issue, level1, gssoc23, FrontEnd

#363 [ADD] User registration and login using Django
  .gitignore
  Backend Code/VigyBag/VigyBag/__pycache__/__init__.cpython-310.pyc
  Backend Code/VigyBag/VigyBag/__pycache__/settings.cpython-310.pyc
  Backend Code/VigyBag/VigyBag/__pycache__/urls.cpython-310.pyc
  Backend Code/VigyBag/VigyBag/__pycache__/wsgi.cpython-310.pyc
  Backend Code/VigyBag/VigyBag/settings.py
  Backend Code/VigyBag/VigyBag/urls.py
  Backend Code/VigyBag/base/__init__.py
  Backend Code/VigyBag/base/__pycache__/__init__.cpython-310.pyc
  Backend Code/VigyBag/base/__pycache__/admin.cpython-310.pyc
  Backend Code/VigyBag/base/__pycache__/apps.cpython-310.pyc
  Backend Code/VigyBag/base/__pycache__/models.cpython-310.pyc
  Backend Code/VigyBag/base/__pycache__/serializers.cpython-310.pyc
  Backend Code/VigyBag/base/__pycache__/urls.cpython-310.pyc
  Backend Code/VigyBag/base/__pycache__/views.cpython-310.pyc
  Backend Code/VigyBag/base/admin.py
  Backend Code/VigyBag/base/apps.py
  Backend Code/VigyBag/base/migrations/0001_initial.py
  Backend Code/VigyBag/base/migrations/__init__.py
  Backend Code/VigyBag/base/migrations/__pycache__/0001_initial.cpython-310.pyc
  Backend Code/VigyBag/base/migrations/__pycache__/__init__.cpython-310.pyc
  Backend Code/VigyBag/base/models.py
  Backend Code/VigyBag/base/serializers.py
  Backend Code/VigyBag/base/tests.py
  Backend Code/VigyBag/base/urls.py
  Backend Code/VigyBag/base/views.py
  Backend Code/VigyBag/db.sqlite3
  login/index.html
  login/script.js
Labels: good first issue, level2, gssoc23, BackEnd

#397 #377 Launcher Icon Added to VigyBag Android
  Android/app/src/main/AndroidManifest.xml
  Android/app/src/main/res/layout/fragment_sign_up.xml
  Android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  Android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Android/app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  Android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  Android/app/src/main/res/mipmap-hdpi/ic_launcher_monochrome.png
  Android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  Android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Android/app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  Android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  Android/app/src/main/res/mipmap-mdpi/ic_launcher_monochrome.png
  Android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  Android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Android/app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  Android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  Android/app/src/main/res/mipmap-xhdpi/ic_launcher_monochrome.png
  Android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Android/app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  Android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  Android/app/src/main/res/mipmap-xxhdpi/ic_launcher_monochrome.png
  Android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  Android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  Android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_monochrome.png
  Android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
Labels: good first issue, level2, gssoc23, android

#405 Added dependabot.yml file
  .github/dependabot.yml
Labels: good first issue, level1, gssoc23, FrontEnd

#470 Added Pop-up `Cart Add Functonality`
  cart/css/style.css
  cart/css/style.scss
  cart/img/cd-icon-arrow-next.svg
  cart/img/cd-icon-select.svg
  cart/img/cd-icons-cart-close.svg
  cart/img/product-preview.png
  cart/js/main.js
  cart/js/util.js
  index.html
  script.js
  style/style.css
Labels: good first issue, level2, gssoc23, FrontEnd

#468 feat: add codeql workflow
  .github/workflows/codeql.yml
Labels: good first issue, level1, gssoc23

#496 Fixed & Upgraded ChatBot
  chatBot/script.js
  chatBot/style.css
  index.html
  style/style.css
Labels: good first issue, level2, gssoc23, FrontEnd

#506 LinkedIn acc and about page linked
  contact/index.html
  index.html
Labels: good first issue, level1, gssoc23, FrontEnd
