Repository codervivek5/VigyBag, pull requests merged in 2023-07, with the labels that each got.

#522 Added Products Popup Details
  chatBot/script.js
  index.html
  script.js
  style/style.css
Labels: good first issue, level1, gssoc23

#505 added spaces on header button
  index.html
  style/style.css
Labels: good first issue, level1, gssoc23, FrontEnd

#551 Backend code for Facebook login
  Backend Code/VigyBag/VigyBag/settings.py
  Backend Code/VigyBag/VigyBag/urls.py
  Backend Code/VigyBag/db.sqlite3
  Backend Code/VigyBag/templates/base.html
  Backend Code/VigyBag/templates/home.html
Labels: good first issue, level2, gssoc23, BackEnd

#568 #562 Navigation Graph issues fixed
  Android/app/src/main/java/com/vigbag/android/MainActivity.kt
  Android/app/src/main/java/com/vigbag/android/SignInFragment.kt
  Android/app/src/main/java/com/vigbag/android/SignUpFragment.kt
  Android/build.gradle
Labels: level1, gssoc23, android

#573 Twitter login frontend
  Backend Code/VigyBag/VigyBag/settings.py
  Backend Code/VigyBag/db.sqlite3
  Backend Code/VigyBag/requirements.txt
  login/index.html
  login/style.css
Labels: good first issue, level1, gssoc23, FrontEnd

#602 updated bottom to top button and all scroll bar get removed from website
  chatBot/style.css
  img/iphone.png
  index.html
  style/style.css
Labels: good first issue, level1, gssoc23, FrontEnd

#607 Improved the SEO Score
  index.html
Labels: enhancement, good first issue, level1, gssoc23, FrontEnd

#326 Added current location page
  currentLocation.html
Labels: good first issue, level2, gssoc23

#555 Fixed FAQ section
  style/style.css
Labels: bug, good first issue, level1, gssoc23, FrontEnd

#462 Dark Mode Bug*
  index.html
  style/style.css
Labels: bug, good first issue, level1, gssoc23, FrontEnd

#617 Backend Code for Contact Us page
  Backend Code/VigyBag/Contact/__init__.py
  Backend Code/VigyBag/Contact/admin.py
  Backend Code/VigyBag/Contact/apps.py
  Backend Code/VigyBag/Contact/migrations/0001_initial.py
  Backend Code/VigyBag/Contact/migrations/__init__.py
  Backend Code/VigyBag/Contact/models.py
  Backend Code/VigyBag/Contact/tests.py
  Backend Code/VigyBag/Contact/urls.py
  Backend Code/VigyBag/Contact/views.py
  Backend Code/VigyBag/VigyBag/__pycache__/__init__.cpython-311.pyc
  Backend Code/VigyBag/VigyBag/__pycache__/settings.cpython-311.pyc
  Backend Code/VigyBag/VigyBag/__pycache__/urls.cpython-311.pyc
  Backend Code/VigyBag/VigyBag/__pycache__/wsgi.cpython-311.pyc
  Backend Code/VigyBag/VigyBag/settings.py
  Backend Code/VigyBag/VigyBag/urls.py
  Backend Code/VigyBag/db.sqlite3
Labels: good first issue, level3, gssoc23, BackEnd

#309 Resolve issue no. #305 Add favicon icon.
  img/favicon.png
  index.html
Labels: good first issue, level1, gssoc23, FrontEnd

#320 Application Preview for README file
  .DS_Store
  README.md
  graphics/.DS_Store
  graphics/vigybag_application_preview/.DS_Store
  graphics/vigybag_application_preview/README.md
  graphics/vigybag_application_preview/screenshots/home_page.png
  graphics/vigybag_application_preview/screenshots/product_marketplace.png
  graphics/vigybag_application_preview/screenshots/product_marketplace_2.png
  graphics/vigybag_application_preview/screenshots/sign_in_page.png
  graphics/vigybag_application_preview/screenshots_framed/.DS_Store
  graphics/vigybag_application_preview/screenshots_framed/home_screen.png
  graphics/vigybag_application_preview/screenshots_framed/product_marketplace_screen_2.png
  graphics/vigybag_application_preview/screenshots_framed/product_marketplace_screenshot.png
  graphics/vigybag_application_preview/screenshots_framed/sign_up_screen.png
  graphics/vigybag_application_preview/vigybag_app_preview.png
Labels: good first issue, level2, gssoc23, FrontEnd

#332 Added top padding & height of product container
  style/style.css
Labels: good first issue, level2, gssoc23, FrontEnd

#624 feat: mobile menu
  index.html
  style/style.css
Labels: bug, enhancement, good first issue, level2, gssoc23, FrontEnd

#620 added styles to contact page
  contact/index.html
  contact/style.css
Labels: bug, good first issue, level1, gssoc23, FrontEnd

#639 Login Page
  Backend Code/VigyBag/VigyBag/__pycache__/settings.cpython-311.pyc
  Backend Code/VigyBag/VigyBag/settings.py
  Backend Code/VigyBag/db.sqlite3
  Backend Code/VigyBag/templates/account/login.html
  Backend Code/VigyBag/templates/base.html
Labels: good first issue, level3, gssoc23, BackEnd

#647 now website is not broken issue solved
  index.html
  style/style.css
Labels: bug, good first issue, level2, gssoc23, FrontEnd

#626 fixed logo and added styles to about page
  About Page/index.html
  About Page/style.css
  style/style.css
Labels: good first issue, level2, gssoc23, FrontEnd

#671 bottom scroll bar removed
  index.html
  style/style.css
Labels: bug, good first issue, level2, gssoc23, FrontEnd

#668 Added Fullly Functional Ai chat and voice assistant
  About Page/index.html
  Cart/Cart.html
  contact/index.html
  contact/style.css
  index.html
  login/index.html
  script.js
Labels: good first issue, level3, gssoc23, FrontEnd

#643 added hover effect on arrows
  style/review.css
Labels: bug, good first issue, level1, gssoc23, FrontEnd

#664 Added the Dark Theme
  About Page/index.html
  About Page/script.js
  About Page/style.css
  index.html
  style/style.css
Labels: bug, good first issue, level3, gssoc23, FrontEnd

#673 fixed broken links
  About Page/index.html
  contact/index.html
Labels: bug, good first issue, level1, gssoc23, FrontEnd

#632 Social media links open in new tab now.
  index.html
Labels: bug, good first issue, level1, gssoc23, FrontEnd

#453 Reviewer section added
  index.html
  style/style.css
Labels: bug, good first issue, level2, gssoc23

#710 added back to top button
  Pages/About Page/about.html
  Pages/contact/contact.html
  style.css
Labels: bug, good first issue, level2, gssoc23, FrontEnd

#711 Fixed Broken Footer Section Of About Page
  Pages/About Page/about.html
Labels: bug, good first issue, level1, gssoc23, FrontEnd
