Repository codervivek5/VigyBag, pull requests merged in 2024-07, with the labels that each got.

#1623 Added top to down arrow in vigyBag Page
  src/Layout.jsx
  src/assets/arrow.png
  src/components/DownArrow/downArrow.jsx
  src/pages/Dashboard/Dashboard.jsx
  src/pages/Home/Home.css
  src/pages/Home/Home.jsx
Labels: good first issue, gssoc

#1632 Authentication Added
  backend/controllers/authController.js
  backend/index.js
  backend/models/User.js
  backend/package-lock.json
  backend/package.json
  package-lock.json
  package.json
  src/Layout.jsx
  src/auth/ProtectedRoute.js
  src/main.jsx
  src/pages/Signup/Signup.jsx
Labels: good first issue, level3, gssoc

#1633 Fixed input text color
  src/pages/Home/Home.jsx
Labels: bug, good first issue, level1, gssoc

#1634 Login Authentication Implemented
  backend/controllers/authController.js
  backend/models/User.js
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/Signup/Signup.jsx
Labels: good first issue, level3, gssoc

#1640 Added Chatbox
  src/Layout.jsx
  src/components/ChatBox/ChatBox.jsx
Labels: good first issue, level3, gssoc

#1637 BambooProducts Page Created and Responsive too
  src/components/HomPageCard/CategoryCard.jsx
  src/components/HomPageCard/LatestInMarketCard.jsx
  src/components/Products/Aside.jsx
  src/components/Products/Header.jsx
  src/components/Products/Main.jsx
  src/components/Products/Navbar.jsx
  src/pages/Home/Home.jsx
  src/pages/Order/Cart.jsx
  src/pages/ProductsPage/BambooProducts.jsx
Labels: good first issue, level3, gssoc

#1641 Middlewares Added
  src/App.jsx
  src/MinimalApp.jsx
  src/PrivateRoute.jsx
  src/auth/ProtectedRoute.js
  src/components/Aside/Aside.jsx
  src/main.jsx
  src/pages/Dashboard/Dashboard.jsx
  src/pages/Login/Login.jsx
Labels: good first issue, level3, gssoc, FrontEnd, BackEnd

#1645 dynamic navbar added
  src/components/Aside/Aside.jsx
  src/components/Navbar/Navbar.jsx
  src/pages/Dashboard/Dashboard.jsx
  src/pages/Login/Login.jsx
Labels: good first issue, level3, gssoc

#1646 Added Scroll Down Progress Bar
  src/Layout.jsx
  src/components/progressbar/ScrollProgressBar.css
  src/components/progressbar/ScrollProgressBar.jsx
Labels: good first issue, level3, gssoc

#1656 Made DownArrow Responsive
  src/components/DownArrow/downArrow.jsx
  src/pages/Home/Home.css
Labels: good first issue, level1, gssoc

#1661 Design and styles the FAQ page
  src/pages/FAQ/Faq.jsx
Labels: bug, good first issue, level1, gssoc

#1662 Arrow Color changed
  src/assets/arrow.png
Labels: bug, good first issue, level1, gssoc

#1669 Fix OTP Activity signup page of android
  Android/.idea/vcs.xml
  Android/app/src/main/java/com/example/vigybagg/activity/OTPActivity.kt
Labels: good first issue, level3, gssoc

#1672 admin login backend done
  backend/index.js
  backend/models/Admin.js
  backend/routes/admin.js
  src/Admin/AdminLogin.jsx
  src/Admin/LoggedInContent.jsx
  src/main.jsx
Labels: good first issue, level3, gssoc, BackEnd

#1680 Implemented a Home Screen And Items Layout
  Android/app/src/main/res/layout/fragment_home.xml
  Android/app/src/main/res/layout/items.xml
Labels: good first issue, level3, gssoc

#1690 Added a Slider in Home Page in android and Backend part
  Android/app/build.gradle.kts
  Android/app/src/main/java/com/example/vigybagg/fragments/HomeFragment.kt
  Android/app/src/main/res/drawable/banner1.jpg
  Android/app/src/main/res/drawable/banner2.jpg
  Android/app/src/main/res/drawable/banner3.jpg
  Android/app/src/main/res/drawable/banner4.png
  Android/app/src/main/res/drawable/selected_dot.xml
  Android/app/src/main/res/drawable/unselected_dot.xml
  Android/app/src/main/res/layout/fragment_home.xml
  Android/settings.gradle.kts
Labels: good first issue, level3, gssoc, android

#1687 Removed Duplicate "HOME" Footer link
  src/components/Footer/Footer.jsx
Labels: bug, good first issue, level1, gssoc

#1683 video
  video
Labels: good first issue, level3, gssoc

#1610 Added hover effects on scrollbar thumb
  src/index.css
Labels: good first issue, level1, gssoc

#1696 Server Hosted and bugs removed
  config.js
  controllers/User.controller.js
  controllers/productController.js
  middleware/authMiddleware.js
  models/User.model.js
  package-lock.json
  package.json
  routes/authRoutes.js
  routes/index.js
  routes/productRoutes.js
  server.js
  src/pages/Login/Login.jsx
  src/pages/Signup/Signup.jsx
Labels: good first issue, level3, gssoc, BackEnd

#1701 Admin access and apis added
  backend/controllers/authController.js
  backend/models/User.js
  src/App.jsx
  src/components/Navbar/Navbar.jsx
  src/main.jsx
  src/pages/Login/Login.jsx
Labels: good first issue, level3, gssoc, BackEnd

#1716 Created terms and Condition for new vigyBag
  src/App.jsx
  src/components/Footer/Footer.jsx
  src/pages/TermsAndCondition/TermsAndCondition.jsx
  src/pages/TermsAndCondition/terms.css
Labels: good first issue, level3, gssoc

#1714 replaced fetch with axios
  src/pages/Latest_in_the_Market/ArtSupplies.jsx
  src/pages/Latest_in_the_Market/BambooProducts.jsx
  src/pages/Latest_in_the_Market/CeramicDinnerware.jsx
  src/pages/Latest_in_the_Market/HandMadeSoaps.jsx
  src/pages/Latest_in_the_Market/NaturalCosmetics.jsx
  src/pages/Latest_in_the_Market/OrganicSoaps.jsx
  src/pages/Latest_in_the_Market/OrganicTea.jsx
  src/pages/Latest_in_the_Market/StorageBaskets.jsx
  src/pages/Popular_Categories/Beauty-Wellness.jsx
  src/pages/Popular_Categories/Body-Care.jsx
  src/pages/Popular_Categories/Customized-Gifts.jsx
  src/pages/Popular_Categories/Fashion-Accessories.jsx
  src/pages/Popular_Categories/Food-Beverages.jsx
  src/pages/Popular_Categories/Furniture-Decor.jsx
  src/pages/Popular_Categories/Health-Supplements.jsx
  src/pages/Popular_Categories/Printing-Stationery.jsx
Labels: bug, good first issue, level3, gssoc

#1718 Added cart features
  package-lock.json
  package.json
  src/App.jsx
  src/assets/empty-cart.png
  src/components/Navbar/CartIcon.jsx
  src/components/Navbar/Navbar.jsx
  src/components/Popular_Categories/ProductGrid.jsx
  src/pages/Order/Cart.jsx
  src/pages/Order/CartEmpty.jsx
  src/redux/cartSlice.jsx
  src/redux/store.jsx
Labels: bug, good first issue, level3, gssoc

#1722 Admin Panel
  package-lock.json
  package.json
  src/Admin/Admin_Panel.jsx
  src/Admin/components/Admin_Panel/AddVigyModal.jsx
  src/Admin/components/Admin_Panel/ExportButton.jsx
  src/Admin/components/Admin_Panel/Header.jsx
  src/Admin/components/Admin_Panel/Pagination.jsx
  src/Admin/components/Admin_Panel/ProfileModal.jsx
  src/Admin/components/Admin_Panel/SearchBar.jsx
  src/Admin/components/Admin_Panel/StatsSummary.jsx
  src/Admin/components/Admin_Panel/VigyTable.jsx
  src/App.jsx
Labels: good first issue, level3, gssoc

#1724 Styled the look of Dashboard Page
  src/components/Aside(Dashboard)/Aside.jsx
  src/components/Aside/Aside.jsx
  src/components/Buttons/Logout.jsx
  src/components/Buttons/SeeMore.jsx
  src/components/Dashboard/Banner.jsx
  src/components/Dashboard/Dropdown.jsx
  src/components/Dashboard/Header.jsx
  src/components/Dashboard/SearchBar.jsx
  src/components/Navbar/Navbar.jsx
  src/components/ProductCard/ProductCard.jsx
  src/pages/Dashboard/Dashboard.jsx
Labels: bug, good first issue, level2, gssoc, FrontEnd

#1734 Created Responsive Navbar and redesigned
  src/components/Navbar/Navbar.jsx
Labels: bug, good first issue, level2, gssoc

#1738 Product Registration page of admin
  src/Admin/ProductForm.jsx
  src/Admin/RegistrationForm.jsx
  src/Admin/components/ProductForm/FileInput.jsx
  src/Admin/components/ProductForm/InputField.jsx
  src/Admin/components/ProductForm/PriceInput.jsx
  src/Admin/components/ProductForm/TextArea.jsx
  src/App.jsx
Labels: good first issue, level3, gssoc

#1741 Added Social Media icon
  src/components/Footer/Footer.jsx
  src/components/Footer/image/github (1).png
Labels: good first issue, level1, gssoc

#1746 added shipping details
  src/components/Order/OrderSummary.jsx
  src/pages/Order/Cart.jsx
  src/pages/Order/Checkout.jsx
  src/pages/Payment/Payment.jsx
Labels: good first issue, level3, gssoc

#1762 [Bug]: Design the Login and Sign up Page to new good looking
  src/components/Navbar/UserNavbar .jsx
  src/pages/Login/Login.jsx
  src/pages/Signup/Signup.jsx
Labels: bug, good first issue, level3, gssoc

#1770 Fixed Bugs in All pages of categories pages
  src/assets/Login-cuate.png
  src/assets/Sign-up.png
  src/assets/sign-up-img.png
  src/components/Aside/Aside.jsx
  src/components/Footer/Footer.jsx
  src/components/Navbar/UserNavbar .jsx
  src/components/Popular_Categories/Filters.jsx
  src/components/Popular_Categories/Header.jsx
  src/components/Popular_Categories/ProductGrid.jsx
  src/pages/Certifications/Certifications.jsx
  src/pages/Contacts/Contact.jsx
  src/pages/Dashboard/Dashboard.jsx
  src/pages/EPRPage/EPR_Page.jsx
  src/pages/FAQ/Faq.jsx
  src/pages/Home/Home.jsx
  src/pages/Latest_in_the_Market/ArtSupplies.jsx
  src/pages/Latest_in_the_Market/BambooProducts.jsx
  src/pages/Latest_in_the_Market/CeramicDinnerware.jsx
  src/pages/Latest_in_the_Market/HandMadeSoaps.jsx
  src/pages/Latest_in_the_Market/NaturalCosmetics.jsx
  src/pages/Latest_in_the_Market/OrganicSoaps.jsx
  src/pages/Latest_in_the_Market/OrganicTea.jsx
  src/pages/Latest_in_the_Market/StorageBaskets.jsx
  src/pages/Login/Login.jsx
  src/pages/Order/Cart.jsx
  src/pages/Order/CartEmpty.jsx
  src/pages/Order/MyOrders.jsx
  src/pages/Order/Orderdetails.jsx
  src/pages/Popular_Categories/Beauty-Wellness.jsx
  src/pages/Popular_Categories/Body-Care.jsx
  src/pages/Popular_Categories/Customized-Gifts.jsx
  src/pages/Popular_Categories/Fashion-Accessories.jsx
  src/pages/Popular_Categories/Food-Beverages.jsx
  src/pages/Popular_Categories/Furniture-Decor.jsx
  src/pages/Popular_Categories/Health-Supplements.jsx
  src/pages/Popular_Categories/Printing-Stationery.jsx
  src/pages/Privacy-Policy/privacy.css
  src/pages/Signup/Signup.jsx
  src/pages/TermsAndCondition/TermsAndCondition.jsx
  src/pages/TermsAndCondition/terms.css
Labels: good first issue, level3, gssoc

#1766 login bug fixed redirect and navbar usericon fixed
  src/components/Navbar/AuthButton.jsx
  src/components/Navbar/UserNavbar .jsx
  src/pages/Login/Login.jsx
Labels: bug, good first issue, level3, gssoc, BackEnd

#1778 Added fuzzy search to the website
  package-lock.json
  package.json
  src/components/SearchBar/SearchBar.jsx
Labels: bug, good first issue, level3, gssoc

#1783 [Bug] Fixed the Resposivness of All Pages with fixed Navbar
  src/components/About/Header.jsx
  src/components/Navbar/UserNavbar .jsx
  src/components/Popular_Categories/Filters.jsx
  src/components/Popular_Categories/ProductGrid.jsx
  src/pages/Certifications/Certifications.jsx
  src/pages/Contacts/Contact.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/SearchBar.jsx
  src/pages/ReturnAndCancellation/returnAndCancellation.jsx
Labels: good first issue, level3, gssoc

#1779 Username Functionality added
  backend/controllers/authController.js
  backend/controllers/productController.js
  backend/index.js
  backend/models/Product.js
  backend/routes/index.js
  src/components/Aside/Aside.jsx
  src/components/Buttons/Logout.jsx
  src/components/Dashboard/Aside.jsx
  src/components/Navbar/AuthButton.jsx
  src/components/Navbar/UserNavbar .jsx
  src/components/SearchBar/SearchBar.jsx
  src/pages/Login/Login.jsx
Labels: good first issue, level3, gssoc

#1788 [Bug] corrected the Logout Navbar and some Bug in responsivness
  src/components/Aside/Aside.jsx
  src/components/Navbar/AuthButton.jsx
  src/components/Navbar/MobileMenu.jsx
  src/components/Navbar/UserNavbar .jsx
  src/pages/Order/Cart.jsx
Labels: good first issue, level3, gssoc

#1798 Bug Fixed for login username
  src/components/Aside/Aside.jsx
  src/components/Navbar/AuthButton.jsx
  src/components/Navbar/MobileMenu.jsx
  src/components/Navbar/UserNavbar .jsx
Labels: good first issue, level3, gssoc

#1801 DONE
  src/pages/Certifications/Certifications.jsx
Labels: good first issue, level3, gssoc

#1804 Resolved: Cart functions don't work.
  src/components/Order/OrderSummary.jsx
  src/pages/Order/Cart.jsx
  src/pages/Order/Checkout.jsx
Labels: good first issue, level2, gssoc

#1751 Feat: Send mail on contact submission
  package-lock.json
  package.json
  src/pages/Contacts/Contact.jsx
Labels: bug, good first issue, level3, gssoc

#1813 [Bug] Fixed Bug for ProductsDetails Pages and Added heading to all latest pages
  src/App.jsx
  src/components/Popular_Categories/ProductGrid.jsx
  src/components/Products/ProductDetails.jsx
  src/pages/Home/Home.jsx
  src/pages/Latest_in_the_Market/ArtSupplies.jsx
  src/pages/Latest_in_the_Market/BambooProducts.jsx
  src/pages/Latest_in_the_Market/CeramicDinnerware.jsx
  src/pages/Latest_in_the_Market/HandMadeSoaps.jsx
  src/pages/Latest_in_the_Market/NaturalCosmetics.jsx
  src/pages/Latest_in_the_Market/OrganicSoaps.jsx
  src/pages/Latest_in_the_Market/OrganicTea.jsx
  src/pages/Latest_in_the_Market/StorageBaskets.jsx
Labels: bug, good first issue, level2, gssoc

#1811 Replaced the price from $ to ₹
  package-lock.json
  src/components/Popular_Categories/ProductGrid.jsx
Labels: bug, good first issue, level1, gssoc

#1817 Added OrderTrackingBar
  src/pages/Order/OrderTrackingBar.jsx
  src/pages/Order/Orderdetails.jsx
Labels: good first issue, level2, gssoc

#1846 [Bug] fixed bugs in footer links and added new features in categories…
  src/Admin/ProductForm.jsx
  src/assets/mahima.png
  src/assets/sadaf.png
  src/assets/syed.png
  src/components/About/Networkdiagram.jsx
  src/components/Footer/Footer.jsx
  src/components/Popular_Categories/ProductGrid.jsx
  src/pages/About/AboutUs.jsx
Labels: good first issue, level2, gssoc

#1859 Product Art supplies page (Fixed issue #1858)
  Web UI Assets/Art Supplies.png
Labels: good first issue, level3, gssoc, UI

#1870 Added popup message for login signup , logout and Clear Button Pages
  src/components/Aside/Aside.jsx
  src/components/Buttons/Logout.jsx
  src/components/FeedbackForm/Feedback.jsx
  src/components/Navbar/UserNavbar .jsx
  src/pages/Dashboard/Dashboard.jsx
  src/pages/Login/Login.jsx
  src/pages/Order/Cart.jsx
  src/pages/Signup/Signup.jsx
Labels: bug, good first issue, level3, gssoc

#1872 Vigy Form Page is modified
  package-lock.json
  package.json
  src/Admin/VigyForm.jsx
  src/Admin/components/RegisterAdmin/FileInput.jsx
  src/Admin/components/RegisterAdmin/InputField.jsx
  src/Admin/components/RegisterAdmin/SelectField.jsx
Labels: bug, good first issue, level3, gssoc

#1876 [bug] Fixed bugs in Help Page and Home Page
  src/pages/Help/Help.css
  src/pages/Help/Help.jsx
Labels: bug, good first issue, level2, gssoc

#1873 Certification Page All Done ✅
  package-lock.json
  package.json
  src/pages/Certifications/Certifications.jsx
Labels: bug, good first issue, level2, gssoc

#1849 Added AI Chatbot
  Vigy - 2024 Jul 16.bpz
  src/App.jsx
  src/components/GoToTop/gototop.jsx
Labels: good first issue, level3, gssoc

#1896 Resolved overlapping filter
  src/User/components/Popular_Categories/Filters.jsx
Labels: bug, good first issue, level1, gssoc

#1887 forgot password functionality added
  backend/controllers/passwordResetRoutes.js
  backend/index.js
  backend/models/User.js
  package-lock.json
  src/App.jsx
  src/User/pages/ForgotPasswordForm.jsx
  src/User/pages/ForgotPasswordForm.module.css
  src/User/pages/Login/Login.jsx
Labels: good first issue, level3, gssoc

#1897 ✔️Added Real-Email Functionality
  package-lock.json
  package.json
  src/User/components/FeedbackForm/Feedback.jsx
Labels: good first issue, level3, gssoc

#1917 Admin Login Page
  src/Admin/Pages/AdminLogin.jsx
Labels: good first issue, level3, gssoc

#1914 ➕Provided Complete Email Access to VigyBag!
  src/User/components/FeedbackForm/Feedback.jsx
  src/User/components/FeedbackForm/feedback.css
Labels: good first issue, level3, gssoc

#1920 Admin Feat Added
  backend/controllers/authController.js
  backend/middlewares/Passport.js
  backend/models/User.js
  backend/package-lock.json
  backend/package.json
  backend/routes/authRoutes.js
  backend/routes/passwordResetRoutes.js
  src/Admin/Pages/AdminLogin.jsx
  src/Admin/components/AdminNavbar.jsx
  src/Admin/components/AdminNavbar/AdminNavbar.jsx
  src/App.jsx
  src/User/pages/AdditionalDetails.jsx
  src/User/pages/Admin-Verification/Admin.jsx
  src/User/pages/ForgotPasswordForm.jsx
  src/User/pages/Login/Login.jsx
Labels: good first issue, level3, gssoc

#1902 [FEATURE]: Added cookie consent banner to enhance user experience.
  package-lock.json
  package.json
  src/App.jsx
  src/User/components/cookieconsent.jsx
Labels: good first issue, level3, gssoc

#1924 [Bugs] Added logout sweetAlert , fixed the filter , delete popup , footer ch…
  src/User/components/Aside/Aside.jsx
  src/User/components/Footer/Footer.jsx
  src/User/components/Navbar/UserNavbar.jsx
  src/User/components/Popular_Categories/Filters.jsx
  src/User/pages/Dashboard/Dashboard.jsx
  src/User/pages/Order/Cart.jsx
Labels: bug, good first issue, level2, gssoc

#1927 user Auth page is done
  src/App.jsx
  src/User/pages/Login/Login.jsx
  src/User/pages/Signup/Signup.jsx
  src/User/pages/UserAuth/UserAuth.css
  src/User/pages/UserAuth/UserAuth.jsx
Labels: good first issue, level3, gssoc, UI

#1931 new ui integrated with backend
  package-lock.json
  src/Admin/AdminLayout.jsx
  src/Admin/components/AdminNavbar.jsx
  src/Admin/components/AdminNavbar/AdminNavbar.jsx
  src/App.jsx
  src/PrivateRoute.jsx
  src/User/components/Aside/Aside.jsx
  src/User/components/Buttons/Logout.jsx
  src/User/components/Navbar/AuthButton.jsx
  src/User/components/Navbar/MobileMenu.jsx
  src/User/components/Navbar/UserNavbar.jsx
  src/User/pages/Dashboard/dashboard_cart.jsx
  src/User/pages/UserAuth/UserAuth.jsx
Labels: bug, good first issue, level3, gssoc

#1936 routes of admin registration done
  backend/index.js
  backend/models/AdminRegistration.js
  backend/package-lock.json
  backend/package.json
  backend/routes/adminRegistrationRoutes.js
  src/Admin/AdminRegistration.jsx
  src/Admin/VigyForm.jsx
Labels: good first issue, level3, gssoc, BackEnd

#1938 bugs fixed and new feat added
  package-lock.json
  src/App.jsx
  src/User/components/Navbar/UserNavbar.jsx
  src/User/pages/Admin-Verification/Admin.jsx
  src/User/pages/UserAuth/UserAuth.jsx
Labels: bug, good first issue, level3, gssoc, BackEnd

#1952 New Contact page and footer updated
  src/User/components/Footer/Footer.jsx
  src/User/pages/Contacts/Contact.jsx
Labels: bug, good first issue, level2, gssoc

#1968 fixed wishlist heart , fixed filter in mobile , corrected route name
  src/App.jsx
  src/User/components/Aside/Aside.jsx
  src/User/components/Footer/Footer.css
  src/User/components/Popular_Categories/Filters.jsx
  src/User/components/Popular_Categories/ProductGrid.jsx
  src/User/pages/Dashboard/dashboard-cart.jsx
  src/User/pages/Dashboard/dashboard-order.jsx
  src/User/pages/Dashboard/dashboard-wishlist.jsx
  src/User/redux/wishlist.jsx
Labels: bug, good first issue, level3, gssoc

#1960 admin auth added with new controllers
  backend/controllers/authController.js
  backend/models/Admin.js
  src/App.jsx
Labels: bug, good first issue, level3, gssoc

#1983 [Feature]: Added OTP and auth template updated
  backend/controllers/authController.js
  src/App.jsx
Labels: good first issue, level2, gssoc

#1992 Bug: Made the Auth Page responsive and fixed logo in mobile
  src/User/components/Navbar/NavLogo.jsx
  src/User/pages/UserAuth/UserAuth.jsx
Labels: good first issue, level1, gssoc

#1991 Feature: Download Private Policy Button
  package-lock.json
  package.json
  src/User/pages/Privacy-Policy/Privacy.jsx
Labels: good first issue, level2, gssoc

#1999 Fixed : UserAuth.jsx
  src/User/pages/UserAuth/UserAuth.jsx
Labels: good first issue, level1, gssoc

#2002 pages linked
  src/User/pages/UserAuth/UserAuth.jsx
Labels: good first issue, level1, gssoc

#2005 Refactor product display to use DummyJSON data
  src/User/pages/Latest_in_the_Market/ArtSupplies.jsx
  src/User/pages/Latest_in_the_Market/BambooProducts.jsx
  src/User/pages/Latest_in_the_Market/CeramicDinnerware.jsx
  src/User/pages/Latest_in_the_Market/HandMadeSoaps.jsx
  src/User/pages/Latest_in_the_Market/NaturalCosmetics.jsx
  src/User/pages/Latest_in_the_Market/OrganicSoaps.jsx
  src/User/pages/Latest_in_the_Market/OrganicTea.jsx
  src/User/pages/Latest_in_the_Market/StorageBaskets.jsx
  src/User/pages/Popular_Categories/Beauty-Wellness.jsx
  src/User/pages/Popular_Categories/Body-Care.jsx
  src/User/pages/Popular_Categories/Customized-Gifts.jsx
  src/User/pages/Popular_Categories/Fashion-Accessories.jsx
  src/User/pages/Popular_Categories/Food-Beverages.jsx
  src/User/pages/Popular_Categories/Furniture-Decor.jsx
  src/User/pages/Popular_Categories/Health-Supplements.jsx
  src/User/pages/Popular_Categories/Printing-Stationery.jsx
Labels: good first issue, level3, gssoc

#2001 Update Footer.jsx
  src/User/components/Footer/Footer.jsx
Labels: good first issue, level1, gssoc

#2004 Added Notification Page
  package-lock.json
  src/App.jsx
  src/User/components/Aside/Aside.jsx
  src/User/pages/Dashboard/NotificationPage.jsx
Labels: good first issue, level3, gssoc

#1977 added discord logo
  src/User/components/Footer/Footer.jsx
Labels: good first issue, level1, gssoc

#1966 terms&condition and privacy policy hyperlink added in login page.
  src/User/pages/UserAuth/UserAuth.jsx
Labels: good first issue, level1, gssoc

#2007 fixed Auth page and added wishlist icon in All Mobile
  src/User/components/Navbar/MobileMenu.jsx
  src/User/components/Navbar/UserNavbar.jsx
  src/User/pages/UserAuth/UserAuth.jsx
Labels: good first issue, level1, gssoc

#2018 Teams Updated Page
  package-lock.json
  package.json
  src/User/components/Team/Card.jsx
  src/User/components/Team/Team.jsx
  src/assets/damini.jpg
  src/assets/garima.jpg
Labels: good first issue, level3, gssoc

#2017 fix the spelling error
  src/User/pages/Home/Home.jsx
  src/components/Navbar/UserNavbar.jsx
Labels: good first issue, level1, gssoc

#2009 Added Profile Page
  package-lock.json
  src/App.jsx
  src/User/components/Aside/Aside.jsx
  src/User/pages/Dashboard/ProfilePage.jsx
Labels: good first issue, level3, gssoc

#2008 Fixed auto commenting feature for merged prs
  .github/workflows/auto-comment-pr-merge.yml
Labels: good first issue, level2, gssoc

#2020 Checks Added
  Android/app/build/tmp/compileDebugJavaWithJavac/compileTransaction/stash-dir/ProgressDialogBinding.class.uniqueId4
  backend/index.js
  src/Admin/Pages/VigyForm.css
  src/Admin/Pages/VigyForm.jsx
  src/User/pages/Admin-Verification/Admin.jsx
Labels: good first issue, level3, gssoc

#2024 Blog Pages is Added
  src/App.jsx
  src/User/pages/Blog/Blog.jsx
Labels: good first issue, level3, gssoc

#2022 Career page
  package-lock.json
  package.json
  src/App.jsx
  src/User/components/About/CarrerHeader.jsx
  src/User/pages/Career-Page/careerPage.jsx
  src/assets/Content_Writer.avif
  src/assets/career.png
  src/assets/product-engineering.jpg
  src/assets/uxui designer.jpg
  src/assets/video editing.jpg
Labels: good first issue, level3, gssoc

#2026 Responisve done for all Devices Blog Pages
  src/User/pages/Blog/Blog.jsx
Labels: good first issue, level2, gssoc

#2028 [ New Feature ] - Api added With functionality on Blog Page
  package-lock.json
  package.json
  src/App.jsx
  src/User/components/About/CarrerHeader.jsx
  src/User/components/Popular_Categories/ProductGrid.jsx
  src/User/pages/AdditionalPages/GiftCardPage.jsx
  src/User/pages/Blog/Blog.jsx
  src/User/pages/Career-Page/careerPage.jsx
  src/assets/Content_Writer.avif
  src/assets/career.png
  src/assets/product-engineering.jpg
  src/assets/uxui designer.jpg
  src/assets/video editing.jpg
Labels: good first issue, level3, gssoc

#2032 responsive is fixed which had not done properly
  src/App.jsx
  src/User/pages/Blog/Blog.jsx
Labels: good first issue, level2, gssoc

#2029 Layout: Adjust positioning for better responsiveness
  package-lock.json
  package.json
  src/App.jsx
  src/User/components/Popular_Categories/Filters.jsx
  src/User/components/Popular_Categories/ProductGrid.jsx
  src/User/components/ProductCard/ProductCard.jsx
Labels: good first issue, level3, gssoc

#2038 backend setup added
  backend/models/AdminRegistration.js
  backend/package-lock.json
  backend/package.json
  backend/routes/adminRegistrationRoutes.js
  package-lock.json
  src/Admin/Pages/VigyForm.jsx
Labels: good first issue, level3, gssoc

#2064 Added splash screen (Fixed issue #2053)
  App UI assets/.png
  App UI assets/Splash Screen.png
Labels: good first issue, level3, gssoc, Figma UI

#2063 service page is repsonsived
  src/User/pages/Service-Page/service.jsx
Labels: good first issue, level2, gssoc

#2042 Added form Page (Fixed issue #2052)
  Web UI Assets/Form Page.png
  img/VG Bag logo.png
Labels: good first issue, level3, gssoc

#2040 Admin Authentication Page added(Fixed issue #2039)
  Web UI Assets/Admin Authetication page.png
Labels: good first issue, level3, gssoc

#2041 Shop Owner Page Added(Fixed issue #2050)
  Web UI Assets/Home Page Shop owner.png
Labels: good first issue, level3, gssoc, Figma UI

#2067 Added "Get Started" page (Fixed issue #2054)
  App UI assets/Get started.png
Labels: good first issue, level3, gssoc

#2066 Evnets Page is Added
  src/App.jsx
  src/User/pages/Events/Events.jsx
Labels: good first issue, level3, gssoc

#2080 Sponsorships page is added
  src/User/pages/Sponsorships/Sponsorships.jsx
  src/User/pages/Warranty/Warranty.jsx
Labels: good first issue, level3, gssoc

#2088 corrected emojies in feedback form
  src/User/components/FeedbackForm/Feedback.jsx
Labels: good first issue, level1, gssoc

#2070 Added new Home page for app (Fixed issue #2057)
  App UI assets/Home page.png
Labels: good first issue, level3, gssoc, Figma UI

#2069 Added OTP Verification page(Fixed issue #2056)
  App UI assets/OTP varification.png
Labels: good first issue, level3, gssoc, Figma UI

#2068 Added "Sign Up" page(Fixed issue #2055)
  App UI assets/Sign up screen.png
Labels: good first issue, level3, gssoc, Figma UI

#2086 Added product detail page of app (Fixed issue #2058)
  App UI assets/Product Detail.png
Labels: good first issue, level3, gssoc, Figma UI

#2082 Subscription Page added
  src/User/pages/Subscription/Subscription.jsx
Labels: good first issue, level3, gssoc

#2093 Updated README.md as per the latest changes and rules
  README.md
  src/assets/VIGYBAG LOGO.png
Labels: good first issue, level2, gssoc

#2094 Enhancements to User Experience with Loading Indicators
  package-lock.json
  package.json
  src/App.jsx
  src/User/UserLayout.jsx
  src/User/components/progressbar/Loader.css
  src/User/components/progressbar/Loader.jsx
Labels: good first issue, level3, gssoc

#2083 ProductCare Page is Added
  src/App.jsx
  src/User/pages/ProductCare/ProductCare.jsx
Labels: good first issue, level3, gssoc
