Repository codervivek5/VigyBag, pull requests merged in 2024-06, with the labels that each got.

#1257 Login Page Completed for New VigyBag
  Android/README.md
  Front-with-React/VigyBag/src/assets/offical_logo.png
  Front-with-React/VigyBag/src/assets/sign-up-img.png
  Front-with-React/VigyBag/src/main.jsx
  Front-with-React/VigyBag/src/pages/Login/Login.jsx
Labels: good first issue, level3, gssoc

#1272 Fix Visibility Issue in Contact Page: Adjust Message Box
  Pages/contact/contact.css
Labels: good first issue, level2, gssoc

#1178 Footer Changes #1169
  Pages/Team/team.css
  Pages/Team/team.html
Labels: good first issue, level2, gssoc

#1271 Visible text properly.
  index.css
  index.html
Labels: good first issue, level1, gssoc

#1285 Designed the footer according to the figma design
  Front-with-React/VigyBag/src/components/Footer/Footer.css
  Front-with-React/VigyBag/src/components/Footer/Footer.jsx
  Front-with-React/VigyBag/src/components/Footer/image/ci.png
  Front-with-React/VigyBag/src/components/Footer/image/hi.png
  Front-with-React/VigyBag/src/components/Footer/image/in.png
  Front-with-React/VigyBag/src/components/Footer/image/li.png
  Front-with-React/VigyBag/src/components/Footer/image/logo.png
  Front-with-React/VigyBag/src/components/Footer/image/meta.png
  Front-with-React/VigyBag/src/components/Footer/image/msg.png
  Front-with-React/VigyBag/src/components/Footer/image/tw.png
Labels: good first issue, level3, gssoc

#1259 Added vigybag Payment Page (issue #1068)
  Front-with-React/VigyBag/Web UI Assets/Payment Page.png
Labels: good first issue, level3, gssoc

#1295 Feedback form
  index.css
  index.html
Labels: good first issue, level3, gssoc

#1264 fixed issue of "Login page" is not responsive to chage in width as per different devics. #1247
  Pages/login/login.css
  Pages/login/login.html
Labels: good first issue, level2, gssoc

#1292 Added Check out page (issue #1068)
  Front-with-React/VigyBag/Web UI Assets/Check-out Page.png
Labels: good first issue, level3, gssoc

#1348 [New Vigy Bag] home page done with animations added
  Front-with-React/VigyBag/src/App.jsx
  Front-with-React/VigyBag/src/main.jsx
  Front-with-React/VigyBag/src/pages/Home.jsx
  Front-with-React/VigyBag/src/pages/Home/Home.jsx
  Front-with-React/VigyBag/src/pages/Home/typewriter.css
  Front-with-React/VigyBag/tailwind.config.js
Labels: good first issue, level3, gssoc

#1365 Bug fixed on main,contact and dashbaord page
  Front-with-React/VigyBag/src/main.jsx
  Front-with-React/VigyBag/src/pages/Contacts/Contact.jsx
  Front-with-React/VigyBag/src/pages/Dashboard/Dashboard.jsx
Labels: good first issue, level3, gssoc

#1367 Confirmation page is Done
  Front-with-React/VigyBag/src/assets/TUMBLER.png
  Front-with-React/VigyBag/src/assets/bamboo_left.png
  Front-with-React/VigyBag/src/assets/bamboo_right.png
  Front-with-React/VigyBag/src/assets/cancel.png
  Front-with-React/VigyBag/src/assets/confirm.png
  Front-with-React/VigyBag/src/assets/tick.png
  Front-with-React/VigyBag/src/pages/Cancellation/Cancellation.jsx
  Front-with-React/VigyBag/src/pages/Confirmation/Confirmation.jsx
Labels: good first issue, level3, gssoc

#1371 Backend Node Added
  Backend Code/VigyBag/Backend_NodeJS/config.js
  Backend Code/VigyBag/Backend_NodeJS/controllers/User.controller.js
  Backend Code/VigyBag/Backend_NodeJS/controllers/productController.js
  Backend Code/VigyBag/Backend_NodeJS/middleware/authMiddleware.js
  Backend Code/VigyBag/Backend_NodeJS/models/User.model.js
  Backend Code/VigyBag/Backend_NodeJS/package-lock.json
  Backend Code/VigyBag/Backend_NodeJS/package.json
  Backend Code/VigyBag/Backend_NodeJS/routes/authRoutes.js
  Backend Code/VigyBag/Backend_NodeJS/routes/index.js
  Backend Code/VigyBag/Backend_NodeJS/routes/productRoutes.js
  Backend Code/VigyBag/Backend_NodeJS/server.js
Labels: good first issue, level3, gssoc, BackEnd

#1363 New Vigy Bag
  Front-with-React/VigyBag/src/assets/images/BeautyAndWellness.svg
  Front-with-React/VigyBag/src/assets/images/BodyCare.svg
  Front-with-React/VigyBag/src/assets/images/CustomisedGifts.svg
  Front-with-React/VigyBag/src/assets/images/FashionAndAccessories.svg
  Front-with-React/VigyBag/src/assets/images/FoodAndBeverages.svg
  Front-with-React/VigyBag/src/assets/images/FurnitureAndDecor.png
  Front-with-React/VigyBag/src/assets/images/FurnitureAndDecor.svg
  Front-with-React/VigyBag/src/assets/images/HealthSupplements.svg
  Front-with-React/VigyBag/src/assets/images/PrintingAndStationary.svg
  Front-with-React/VigyBag/src/assets/images/healthcare.png
  Front-with-React/VigyBag/src/assets/images/svg2.svg
  Front-with-React/VigyBag/src/components/HomPageCard/CategoryCard.jsx
  Front-with-React/VigyBag/src/index.css
  Front-with-React/VigyBag/src/pages/Contacts/Contact.jsx
  Front-with-React/VigyBag/src/pages/Home/Home.jsx
  Front-with-React/VigyBag/tailwind.config.js
Labels: good first issue, level3, gssoc

#1383 [New VigyBag] - OrderDetails and MyOrders Page is Done
  Front-with-React/VigyBag/src/assets/Handwoven-Doormat.jpeg
  Front-with-React/VigyBag/src/assets/Storage-basket-and-container.jpeg
  Front-with-React/VigyBag/src/assets/b-tick.png
  Front-with-React/VigyBag/src/assets/map.png
  Front-with-React/VigyBag/src/assets/payment.png
  Front-with-React/VigyBag/src/components/Navbar/Navbar.jsx
  Front-with-React/VigyBag/src/components/Order/ProgressBar.jsx
  Front-with-React/VigyBag/src/main.jsx
  Front-with-React/VigyBag/src/pages/Order/Cart.jsx
  Front-with-React/VigyBag/src/pages/Order/MyOrders.jsx
  Front-with-React/VigyBag/src/pages/Order/Orderdetails.jsx
Labels: good first issue, level3, gssoc

#1386 cart Page is Done
  Front-with-React/VigyBag/src/pages/404-Page/Error.jsx
  Front-with-React/VigyBag/src/pages/Order/Cart.jsx
Labels: good first issue, level3, gssoc

#1336 Updated Check-Out page ( Fixed issue #1068)
  Front-with-React/VigyBag/Web UI Assets/Check-out PageVB.png
Labels: good first issue, level3, gssoc

#1388 Error Page is Done
  Front-with-React/VigyBag/src/pages/404-Page/Error.jsx
Labels: good first issue, level3, gssoc

#1390 Checkout page is done
  Front-with-React/VigyBag/src/pages/Order/Checkout.jsx
Labels: good first issue, level3, gssoc

#1395 Harshita
  Front-with-React/VigyBag/src/assets/images/HandmadeSoaps.svg
  Front-with-React/VigyBag/src/assets/images/svg2.svg
  Front-with-React/VigyBag/src/components/DropDown/DropDown.jsx
  Front-with-React/VigyBag/src/components/HomPageCard/LatestInMarketCard.jsx
  Front-with-React/VigyBag/src/components/Navbar/Navbar.jsx
  Front-with-React/VigyBag/src/pages/Home/Home.jsx
Labels: good first issue, level3, gssoc

#1392 ProductDetails Page is Done
  Front-with-React/VigyBag/src/assets/comb.jpg
  Front-with-React/VigyBag/src/components/Products/ProductDetails.jsx
  Front-with-React/VigyBag/src/components/Products/Similarproducts.jsx
  Front-with-React/VigyBag/src/main.jsx
  Front-with-React/VigyBag/src/pages/Help/Help.jsx
  Front-with-React/VigyBag/src/pages/Payment/Payment.jsx
  Front-with-React/VigyBag/src/pages/Privacy-Policy/Privacy.jsx
Labels: good first issue, level3, gssoc

#1402 Payment Page is Done
  Front-with-React/VigyBag/src/components/Footer/Footer.jsx
  Front-with-React/VigyBag/src/components/Navbar/Navbar.jsx
  Front-with-React/VigyBag/src/pages/Payment/Payment.jsx
Labels: good first issue, level3, gssoc

#1409 Responsive Navbar Is Done
  Front-with-React/VigyBag/src/components/Navbar/Navbar.jsx
Labels: good first issue, level3, gssoc

#1407 Added Confirmation Page (Fixed Issue #1380)
  Front-with-React/VigyBag/Web UI Assets/Confirmation Page.png
Labels: good first issue, level3, gssoc

#1411 Responsive Footer is Done
  Front-with-React/VigyBag/src/components/DropDown/DropDown.jsx
  Front-with-React/VigyBag/src/components/Footer/Footer.css
  Front-with-React/VigyBag/src/components/Footer/Footer.jsx
Labels: good first issue, level3, gssoc

#1414 Responsive Cart is Done
  Front-with-React/VigyBag/src/pages/Order/Cart.jsx
Labels: good first issue, level3, gssoc

#1416 Responsive Checkout Page Is Done
  Front-with-React/VigyBag/src/components/Order/ProgressBar.css
  Front-with-React/VigyBag/src/components/Order/ProgressBar.jsx
  Front-with-React/VigyBag/src/pages/Order/Checkout.jsx
Labels: good first issue, level3, gssoc, android

#1417 Fix:Add icon
  Pages/contact/contact.html
  Pages/login/login.html
Labels: good first issue, level2, gssoc

#1427 Changed price styling !!
  Pages/About Page/about.css
  Pages/About Page/about.html
  Pages/About Page/about.js
  index.html
  package-lock.json
  package.json
  style/style.css
Labels: good first issue, level2, gssoc

#1431 Added cross origins connection
  Backend Code/Backend_NodeJS/server.js
Labels: good first issue, level3, gssoc

#1419 Responsive payment is Done
  Front-with-React/VigyBag/src/pages/Payment/Payment.jsx
Labels: good first issue, level3, gssoc

#1437 Feedback form UI improved
  index.css
Labels: good first issue, level2, gssoc

#1439 Responsive MyOrder Page is Done
  Front-with-React/VigyBag/src/pages/Order/Cart.jsx
  Front-with-React/VigyBag/src/pages/Order/MyOrders.jsx
Labels: good first issue, level3, gssoc

#1440 Responsive Contact page is Done
  Front-with-React/VigyBag/src/pages/Contacts/Contact.jsx
  Front-with-React/VigyBag/src/pages/Order/MyOrders.jsx
Labels: good first issue, level3, gssoc

#1442 Responsive Login Page is Done
  Front-with-React/VigyBag/src/pages/Login/Login.jsx
  Front-with-React/VigyBag/src/pages/Order/MyOrders.jsx
Labels: good first issue, level3, gssoc

#1445 Scroll Bar Added
  Front-with-React/VigyBag/src/index.css
Labels: good first issue, level3, gssoc

#1447 Routing fixed
  Front-with-React/VigyBag/src/components/Navbar/Navbar.jsx
  Front-with-React/VigyBag/src/main.jsx
  Front-with-React/VigyBag/src/pages/Categories/BodyCare.jsx
  Front-with-React/VigyBag/src/pages/Categories/Categories.jsx
  Front-with-React/VigyBag/src/pages/Categories/Fashion.jsx
  Front-with-React/VigyBag/src/pages/Categories/Furniture.jsx
  Front-with-React/VigyBag/src/pages/Categories/Gifts.jsx
  Front-with-React/VigyBag/src/pages/Categories/Stationary.jsx
  Front-with-React/VigyBag/src/pages/Category/DecorativeItems.jsx
Labels: good first issue, level3, gssoc

#1455 Added Product Details Page (Fixed issue #1454)
  Front-with-React/VigyBag/Web UI Assets/Product Details2.png
Labels: good first issue, level3, gssoc

#1457 Navbar Bug Fixed
  Front-with-React/VigyBag/src/components/Footer/Footer.css
  Front-with-React/VigyBag/src/components/Footer/Footer.jsx
  Front-with-React/VigyBag/src/components/Navbar/Navbar.jsx
Labels: good first issue, level2, gssoc

#1467 Home Page is Done
  Front-with-React/VigyBag/src/assets/ANSHUMAN-TIWARI.png
  Front-with-React/VigyBag/src/assets/ANUJA-SINGH.png
  Front-with-React/VigyBag/src/assets/Art-Supplies.png
  Front-with-React/VigyBag/src/assets/Bamboo-Products.png
  Front-with-React/VigyBag/src/assets/Beauty-Wellness.png
  Front-with-React/VigyBag/src/assets/Body-Care.png
  Front-with-React/VigyBag/src/assets/Ceramic-Dinnerware.png
  Front-with-React/VigyBag/src/assets/Customized-Gifts.png
  Front-with-React/VigyBag/src/assets/Fashion-Accessories.png
  Front-with-React/VigyBag/src/assets/Food-Beverages.png
  Front-with-React/VigyBag/src/assets/Furniture-Decor.jpeg
  Front-with-React/VigyBag/src/assets/Handmade-Soaps.png
  Front-with-React/VigyBag/src/assets/Health-supplements.png
  Front-with-React/VigyBag/src/assets/Printing-Stationary.png
  Front-with-React/VigyBag/src/assets/Storage-Baskets.png
  Front-with-React/VigyBag/src/assets/YATRA-VISHWAKARMA.png
  Front-with-React/VigyBag/src/assets/background.png
  Front-with-React/VigyBag/src/assets/co-founder.jpeg
  Front-with-React/VigyBag/src/assets/founder.jpeg
  Front-with-React/VigyBag/src/assets/google-play.png
  Front-with-React/VigyBag/src/assets/images/BeautyAndWellness.svg
  Front-with-React/VigyBag/src/assets/images/BodyCare.svg
  Front-with-React/VigyBag/src/assets/images/CustomisedGifts.svg
  Front-with-React/VigyBag/src/assets/images/FashionAndAccessories.svg
  Front-with-React/VigyBag/src/assets/images/FoodAndBeverages.svg
  Front-with-React/VigyBag/src/assets/images/FurnitureAndDecor.png
  Front-with-React/VigyBag/src/assets/images/FurnitureAndDecor.svg
  Front-with-React/VigyBag/src/assets/images/HandmadeSoaps.svg
  Front-with-React/VigyBag/src/assets/images/HealthSupplements.svg
  Front-with-React/VigyBag/src/assets/images/PrintingAndStationary.svg
  Front-with-React/VigyBag/src/assets/images/background.png
  Front-with-React/VigyBag/src/assets/images/healthcare.png
  Front-with-React/VigyBag/src/assets/mobile.png
  Front-with-React/VigyBag/src/assets/tanmay.jpg
  Front-with-React/VigyBag/src/components/HomPageCard/CategoryCard.jsx
  Front-with-React/VigyBag/src/components/HomPageCard/LatestInMarketCard.jsx
  Front-with-React/VigyBag/src/main.jsx
  Front-with-React/VigyBag/src/pages/Home/Home.jsx
Labels: good first issue, level3, gssoc

#1469 firebase configs added
  Backend Code/Backend_NodeJS/firebaseConfig.js
  Backend Code/Backend_NodeJS/package-lock.json
  Backend Code/Backend_NodeJS/package.json
  Front-with-React/VigyBag/package-lock.json
  Front-with-React/VigyBag/package.json
  Front-with-React/VigyBag/src/Configs/FirebaseConfig.js
  Front-with-React/VigyBag/src/pages/Login/Login.jsx
Labels: good first issue, level3, gssoc

#1475 Responsive Homepage is Done
  Front-with-React/VigyBag/src/components/About/ContributorCard.jsx
  Front-with-React/VigyBag/src/components/HomPageCard/CategoryCard.jsx
  Front-with-React/VigyBag/src/components/HomPageCard/LatestInMarketCard.jsx
  Front-with-React/VigyBag/src/pages/About/AboutUs.jsx
  Front-with-React/VigyBag/src/pages/Home/Home.jsx
Labels: good first issue, level3, gssoc

#1473 Enhanced the privacy page in new VigyBag
  Front-with-React/VigyBag/src/components/Footer/Footer.jsx
  Front-with-React/VigyBag/src/pages/Privacy-Policy/Privacy.jsx
  Front-with-React/VigyBag/src/pages/Privacy-Policy/privacy.css
  Front-with-React/VigyBag/src/pages/Privacy-Policy/style.css
Labels: good first issue, level3, gssoc

#1480 Responsive Home page is Done
  Front-with-React/VigyBag/src/components/HomPageCard/CategoryCard.jsx
  Front-with-React/VigyBag/src/components/HomPageCard/LatestInMarketCard.jsx
  Front-with-React/VigyBag/src/pages/Home/Home.jsx
Labels: good first issue, level3

#1503 corrected the box
  src/pages/Privacy-Policy/Privacy.jsx
  src/pages/Privacy-Policy/privacy.css
Labels: bug, good first issue, level2, gssoc

#1513 Handmade soap category page( Fixed issue #1511)
  Web UI Assets/Products(Handmade soap ).png
Labels: good first issue, level3, gssoc

#1514 Storage basket page (Fixed issue #1511)
  Web UI Assets/Storage Basket.png
Labels: good first issue, level3, gssoc

#1535 Responisve productDetails is done With Navbar is Added
  package-lock.json
  src/assets/images/Logo.svg
  src/components/Navbar/Navbar.jsx
  src/components/Products/ProductDetails.jsx
  src/components/Products/Similarproducts.jsx
  src/main.jsx
  src/pages/Order/Cart.jsx
Labels: good first issue, level3, gssoc

#1515 Category 3- ceramic Page first Draft (Fixed issue #1511)
  Web UI Assets/Ceramic !.png
Labels: good first issue, level3, gssoc

#1516 Updated ceramic Page ( Fixed issue #1511)
  Web UI Assets/Ceramic 2.png
Labels: good first issue, level3, gssoc

#1550 Home page bug solved
  src/components/HomPageCard/CategoryCard.jsx
  src/pages/Home/Home.jsx
Labels: good first issue, level3, gssoc

#1557 Return cancellation page is responsive
  src/assets/ANUJA-SINGH.png
  src/assets/ARCHANA-KRISHNA.png
  src/assets/HARSHITA-BHAMBHANI.png
  src/assets/YATRA-VISHWAKARMA.png
  src/assets/co-founder.jpeg
  src/assets/tanmay.jpg
  src/main.jsx
  src/pages/Contacts/Contact.jsx
  src/pages/Login/Login.jsx
  src/pages/ReturnAndCancellation/returnAndCancellation.jsx
  src/pages/Signup/Signup.jsx
Labels: good first issue, level3, gssoc

#1562 About modified
  src/components/ContributorCard/ContributorCard.jsx
  src/pages/About/AboutUs.jsx
Labels: good first issue, level2, gssoc

#1571 backend setup added
  backend/controllers/authController.js
  backend/index.js
  backend/models/User.js
  backend/package-lock.json
  backend/package.json
  backend/routes/authRoutes.js
  backend/routes/index.js
  backend/routes/productRoutes.js
Labels: good first issue, level3, gssoc

#1574 Styled the Navbar in vigyBag
  index.html
  src/components/Navbar/Navbar.jsx
Labels: good first issue, level3, gssoc

#1578 Frontend enhanced and structered accordingly to backend structure
  src/pages/About/AboutUs.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/Signup/Signup.jsx
Labels: good first issue, level3, gssoc

#1582 Responsive EPR page
  src/pages/EPRPage/EPR_Page.jsx
Labels: good first issue, level2, gssoc

#1505 Update README.md
  README.md
Labels: good first issue, level2, gssoc

#1565 Added clearCart Button
  src/pages/Order/Cart.jsx
Labels: good first issue, level2, gssoc

#1584 Added "Smooth Scroll Behavior" for Footer Links
  src/components/Footer/Footer.jsx
Labels: good first issue, level2, gssoc

#1572 Added "Scroll-to-Top" Button to new VigyBag Website
  package-lock.json
  package.json
  src/Layout.jsx
  src/components/gototop.jsx
Labels: good first issue, level3, gssoc

#1589 Modified Cancellation page
  src/pages/Cancellation/Cancellation.jsx
Labels: bug, good first issue, level2, gssoc, FrontEnd

#1607 Modified the looking of footer in vigyBag
  package-lock.json
  package.json
  src/components/Footer/Footer.jsx
  src/components/GoToTop/gototop.jsx
Labels: bug, good first issue, level2, gssoc

#1592 Update README.md
  README.md
Labels: good first issue, level2, gssoc

#1599 Made the changes in the cart
  src/pages/Order/Cart.jsx
Labels: bug, good first issue, level2, gssoc

#1611 Modified About Page
  src/assets/co-founder.jpeg
  src/assets/founder.jpeg
  src/components/ContributorCard/ContributorCard.jsx
  src/components/GoToTop/gototop.jsx
  src/components/Networkdiagram/Networkdiagram.jsx
  src/pages/About/AboutUs.jsx
  src/pages/Home/Home.jsx
Labels: bug, good first issue, level3, gssoc
