Repository codervivek5/VigyBag, pull requests merged in 2024-08, with the labels that each got.

#2097 Created Shipping page of vigybag
  src/App.jsx
  src/User/components/FeedbackForm/Feedback.jsx
  src/User/components/Footer/Footer.jsx
  src/User/pages/Shipping/shipping.jsx
Labels: good first issue, level3, gssoc

#2102 Made Career Page responsive
  src/User/components/About/CarrerHeader.jsx
  src/User/pages/Career-Page/careerPage.jsx
Labels: good first issue, level2, gssoc

#2113 vigy for admin backend
  backend/models/AdminRegistration.js
  backend/routes/adminRegistrationRoutes.js
  src/Admin/Pages/VigyForm.jsx
Labels: good first issue, level3, gssoc, BackEnd

#2118 Modified the Profile Page of vigybag
  src/User/pages/Dashboard/ProfilePage.jsx
  src/User/pages/Dashboard/profile.css
  src/assets/copy.png
Labels: good first issue, level2, gssoc

#2109 Added check-out page (Fixed issue #2108)
  App UI assets/checkout.png
Labels: good first issue, level3, gssoc

#2126 Forget Password page Updated
  src/User/pages/ForgotPasswordForm.jsx
  src/assets/images/forget-ill.svg
Labels: good first issue, level2, gssoc

#2127 Making Cart and Wishlist Visible in Mobile view
  src/User/components/Navbar/UserNavbar.jsx
Labels: good first issue, level1, gssoc

#2122 Admin Navbar fixed
  src/Admin/components/AdminNavbar/AdminNavbar.jsx
Labels: good first issue, level2, gssoc

#2120 Made Product detail page dynamic
  package-lock.json
  src/App.jsx
  src/User/components/Popular_Categories/ProductGrid.jsx
  src/User/components/Products/ProductDetails.jsx
  src/User/components/Products/Similarproducts.jsx
  src/User/pages/Order/Wishlist.jsx
  src/User/pages/Popular_Categories/Beauty-Wellness.jsx
  src/User/pages/Popular_Categories/Body-Care.jsx
  src/User/pages/Popular_Categories/Customized-Gifts.jsx
  src/User/pages/Popular_Categories/Fashion-Accessories.jsx
  src/User/pages/Popular_Categories/Food-Beverages.jsx
  src/User/pages/Popular_Categories/Furniture-Decor.jsx
  src/User/pages/Popular_Categories/Health-Supplements.jsx
  src/User/pages/Popular_Categories/Printing-Stationery.jsx
  src/User/redux/cartSlice.jsx
Labels: good first issue, level3, gssoc, FrontEnd

#2136 Created new Gift Card Page of VigyBag
  src/App.jsx
  src/User/components/About/GiftHeader.jsx
  src/User/components/Footer/Footer.jsx
  src/User/components/Navbar/UserNavbar.jsx
  src/User/pages/Gift-Card/gift-card.jsx
  src/assets/anniversary.webp
  src/assets/best wishes.jpg
  src/assets/birthday-gifts.webp
  src/assets/cake.jpg
  src/assets/clap.avif
  src/assets/flowers.avif
  src/assets/gift.jpg
  src/assets/giftcard.jpg
  src/assets/gifts.jpg
  src/assets/laddo.png
  src/assets/thank you.jpg
  src/assets/wedding.webp
  src/assets/yellow_page.png
Labels: good first issue, level3, gssoc

#2137 Fix - Product image not showing in the cart and wishlist
  src/User/components/Products/ProductDetails.jsx
  src/User/pages/Order/Wishlist.jsx
  src/User/redux/cartSlice.jsx
Labels: good first issue, level3, gssoc

#2134 Add Scroll Progress Indicator to "Go To Top" Button and Remove react-top-loader
  package-lock.json
  package.json
  src/User/UserLayout.jsx
  src/User/components/GoToTop/gototop.jsx
  src/User/components/GoToTop/top.css
  src/User/components/progressbar/Loader.jsx
  src/User/components/progressbar/ScrollProgressBar.css
Labels: good first issue, level3, gssoc

#2148 Debugged the price display on Art Supplies page.
  src/User/pages/Latest_in_the_Market/ArtSupplies.jsx
Labels: good first issue, level1, gssoc

#2139 Added checkout page updated (fixed issue #2138)
  App UI assets/checkout updated.png
Labels: good first issue, level3, gssoc

#2141 Added updated cart page(Fixed issue #2140)
  App UI assets/My Cart updated.png
Labels: good first issue, level3, gssoc

#2163 Created Deactivate and delete form for VigyBag Account
  package-lock.json
  package.json
  src/User/components/Footer/Footer.jsx
  src/User/pages/Dashboard/ProfilePage.jsx
  src/User/pages/Dashboard/model.css
Labels: good first issue, level3, gssoc

#2173 feat: Add alphanumeric password check and password strength indicator
  src/User/pages/UserAuth/UserAuth.jsx
Labels: good first issue, level2, gssoc

#2176 Added Wishlist Page (Fixed issue #2175)
  App UI assets/Wishlist Page.png
Labels: good first issue, level3, gssoc

#2179 Add required fields and validation checks to contact form
  src/User/pages/Contacts/Contact.jsx
Labels: good first issue, level3, gssoc

#2164 ✔️Added Dynamic "Last Updated" Functionality to All Legal Pages!
  src/User/pages/Privacy-Policy/Privacy.jsx
  src/User/pages/Privacy-Policy/privacy.css
  src/User/pages/TermsAndCondition/TermsAndCondition.jsx
  src/User/pages/TermsAndCondition/terms.css
Labels: good first issue, level3, gssoc

#2178 Added Payment Page in VigyBag
  src/App.jsx
  src/User/components/Footer/Footer.jsx
  src/User/pages/Payment-Policy/payment-policy.jsx
Labels: good first issue, level3, gssoc

#2131 Adding Facebook Authentication
  package-lock.json
  package.json
  src/User/pages/UserAuth/UserAuth.jsx
  src/User/pages/UserAuth/firebase.js
  src/User/pages/UserAuth/package.json
Labels: good first issue, level3, gssoc

#2186 Enhanced The Orders Page
  package-lock.json
  src/User/pages/Dashboard/dashboard-order.jsx
Labels: good first issue, level2, gssoc

#2191 gifts card page is created and well responsive
  src/User/pages/Subscription/Subscription.jsx
  src/assets/mastercard.png
  src/assets/visa.png
Labels: good first issue, level2, gssoc

#2198 Implement dynamic category filtering across all listing pages
  src/User/components/Popular_Categories/Filters.jsx
  src/User/pages/Latest_in_the_Market/ArtSupplies.jsx
  src/User/pages/Latest_in_the_Market/BambooProducts.jsx
  src/User/pages/Latest_in_the_Market/CeramicDinnerware.jsx
  src/User/pages/Latest_in_the_Market/HandMadeSoaps.jsx
  src/User/pages/Latest_in_the_Market/NaturalCosmetics.jsx
  src/User/pages/Latest_in_the_Market/OrganicSoaps.jsx
  src/User/pages/Latest_in_the_Market/OrganicTea.jsx
  src/User/pages/Latest_in_the_Market/StorageBaskets.jsx
  src/User/pages/Popular_Categories/Beauty-Wellness.jsx
  src/User/pages/Popular_Categories/Body-Care.jsx
  src/User/pages/Popular_Categories/Customized-Gifts.jsx
  src/User/pages/Popular_Categories/Fashion-Accessories.jsx
  src/User/pages/Popular_Categories/Food-Beverages.jsx
  src/User/pages/Popular_Categories/Furniture-Decor.jsx
  src/User/pages/Popular_Categories/Health-Supplements.jsx
  src/User/pages/Popular_Categories/Printing-Stationery.jsx
Labels: good first issue, level3, gssoc
