Repository codervivek5/VigyBag, pull requests merged in 2024-10, with the labels that each got.

#2323 Added shadow to vigybag logo
  src/User/components/Footer/Footer.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#2325 corrected the cards of the categories
  src/User/components/Popular_Categories/ProductGrid.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#2330 🛠️ Fix: Name Field validation in Feedback page
  src/User/components/FeedbackForm/Feedback.jsx
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#2333 🛠️ FIX : First Name Field validation in Contact us page
  src/User/pages/Contacts/Contact.jsx
Labels: hacktoberfest, hacktoberfest-accepted

#2334 🛠️ FIX : Last Name Field validation in Contact us page
  src/User/pages/Contacts/Contact.jsx
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#2293 Navbar Issue Fixed
  .idea/workspace.xml
  Android/.idea/.gitignore
  Android/.idea/deploymentTargetSelector.xml
  Android/.idea/gradle.xml
  Android/.idea/misc.xml
  Android/.idea/modules.xml
  Android/.idea/vcs.xml
  Android/.idea/workspace.xml
  src/User/components/Navbar/UserNavbar.jsx
  src/components/Navbar/UserNavbar.jsx
Labels: gssoc, hacktoberfest, hacktoberfest-accepted, Gssoc-ext

#2335 Added borders to product detail page
  src/User/components/Popular_Categories/ProductGrid.jsx
  src/User/components/Products/ProductDetails.jsx
Labels: good first issue, gssoc, hacktoberfest, hacktoberfest-accepted, gssoc-ext

#2348 Corrected the Home page and Dashboard page
  src/User/components/Aside/Aside.jsx
  src/User/pages/Dashboard/Dashboard.jsx
  src/User/pages/Home/Home.jsx
Labels: good first issue, gssoc, hacktoberfest, hacktoberfest-accepted, gssoc-ext

#2418 Added Hovering effect to social icons in Footer issue -#2388
  src/App.jsx
  src/User/components/Footer/Footer.css
  src/User/components/Footer/Footer.jsx
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#2421 Added a light box shadow for divs in popular categories section issue - #2390
  src/User/pages/Home/Home.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#2424 Issue #2391 changed button color in whishlist
  src/User/pages/Dashboard/dashboard-wishlist.jsx
  src/User/pages/Order/WishlistEmpty.jsx
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
