Repository codervivek5/VigyBag, pull requests merged in 2024-05, with the labels that each got.

#982 updating requirements.txt
  Backend Code/VigyBag/requirements.txt
Labels: gssoc24, BackEnd, easy

#992 What Do Our Costumers Say Page Improvement DONE
  Pages/review/review.css
  Pages/review/review.js
  index.css
  index.html
Labels: bug, good first issue, gssoc24, FrontEnd, easy

#1013 enchanced the services hover effect
  style/style.css
Labels: enhancement, good first issue, gssoc24, FrontEnd, easy

#1037 Renamed "Our Service" to "Categories"
  index.html
Labels: good first issue, level1, gssoc

#1049 docs: make issue template working
  .github/ISSUES_TEMPLATE/Other.yml
  .github/ISSUES_TEMPLATE/bug.yml
  .github/ISSUES_TEMPLATE/documentation.yml
  .github/ISSUES_TEMPLATE/feature.yml
  README.md
Labels: good first issue, level1, gssoc

#1077 Fixed Navigation Bar Text Visibility Issue in Dark Mode in Team Tab
  Pages/Team/team.css
Labels: good first issue, level2, gssoc

#1095 Added Animated icon to the Navbar links
  index.html
  style/style.css
Labels: good first issue, level2, gssoc

#1103 Fixed issue #1067
  Front-with-React/VigyBag/Assets/Logo/VB logo 1.png
  Front-with-React/VigyBag/Assets/Logo/VB logo 2.png
  Front-with-React/VigyBag/Assets/Logo/VB logo 3.png
  Front-with-React/VigyBag/Assets/Logo/VB logo 4.png
  Front-with-React/VigyBag/Assets/Logo/VB logo 5.png
Labels: good first issue, level3, gssoc

#1110 Added answers in FAQ section of the page
  index.html
  style/style.css
Labels: good first issue, level2, gssoc

#1088 Search bar issue has resolved #1026
  index.html
  style/style.css
Labels: bug, good first issue, level2, gssoc

#1117 Added Different images to the headphones section
  img/head1.jpg
  img/head2.jpeg
  img/head3.jpg
  img/head4.webp
  img/head5.webp
  img/head6.webp
  index.html
Labels: bug, good first issue, level2, gssoc

#1076 Fixed the Google Sign In hovering issue
  Pages/login/login.css
  Pages/login/login.html
Labels: bug, good first issue, level1, gssoc

#1070 Fixed Issue #1018 in the cart section
  see_more/cart/main.js
  see_more/see_more.html
Labels: bug, good first issue, level2, gssoc

#1125 Gssoc level2 kapil (Issue 1079)
  Pages/contact/contact.css
  style/style.css
Labels: good first issue, level2, gssoc

#1123 animation added
  index.html
  package-lock.json
Labels: good first issue, level3, gssoc

#1155 Redesigned UI (Sign Up Page)
  Front-with-React/VigyBag/Web UI Assets/Sign Up Page VB.png
Labels: good first issue, level2, gssoc

#1161 Edited dynamic code for year in footer section
  index.html
Labels: good first issue, level2, gssoc

#1187 Added My Cart Page
  Cart/script.js
  cart/js/util.js
  index.html
Labels: good first issue, level2, gssoc

#1171 Home Page UI (Issue #1068)
  Front-with-React/VigyBag/Web UI Assets/Home VB.png
Labels: good first issue, level3, gssoc

#1200 Added User Dashboard Page (issue #1068)
  Front-with-React/VigyBag/Web UI Assets/User Dashboard.png
Labels: good first issue, level3, gssoc

#1201 Added Contact Page(issue #1068)
  Front-with-React/VigyBag/Web UI Assets/Contact.png
Labels: good first issue, level3, gssoc

#1202 Cart Page Added ( issue #1068)
  Front-with-React/VigyBag/Web UI Assets/Cart VB.png
Labels: good first issue, level3, gssoc

#1210 Harshita
  Front-with-React/VigyBag/package-lock.json
  Front-with-React/VigyBag/package.json
  Front-with-React/VigyBag/src/App.css
  Front-with-React/VigyBag/src/App.jsx
  Front-with-React/VigyBag/src/assets/images/background.png
  Front-with-React/VigyBag/src/assets/react.svg
  Front-with-React/VigyBag/src/components/Navbar/Navbar.jsx
  Front-with-React/VigyBag/src/index.css
  Front-with-React/VigyBag/src/main.jsx
  Front-with-React/VigyBag/src/pages/AboutUs.jsx
  Front-with-React/VigyBag/src/pages/Categories.jsx
  Front-with-React/VigyBag/src/pages/Dashboard.jsx
  Front-with-React/VigyBag/src/pages/Gifts.jsx
  Front-with-React/VigyBag/src/pages/LadingPage.jsx
Labels: good first issue, level3, gssoc, FrontEnd

#1214 Added auto commenting feature on issue creation
  .github/workflows/auto-comment-issue.yml
Labels: good first issue, level3, gssoc

#1182 Improve Mobile Section with New Images and Enhanced Styling #1134
  img/mo1.png
  img/mo10.png
  img/mo11.png
  img/mo2.avif
  img/mo3.avif
  img/mo4.webp
  img/mo5.png
  img/mo6.png
  img/mo7.png
  img/mo8.png
  img/mo9.png
  img/vigybag_design-removebg-preview 1.png
  img/vigybag_icon-removebg-preview (1) 1.png
  index.css
  index.html
  see_more/see_more.html
  style/style.css
Labels: good first issue, level2, gssoc

#1101 Fixed issue #1067 ( VB seperate logos)
  img/VB logo 1.png
  img/VB logo 2.png
  img/VB logo 3.png
  img/VB logo 4.png
  img/VB logo 5.png
Labels: good first issue, level2, gssoc

#1229 Added styles to the about us page #1168
  Pages/About Page/about.css
  Pages/About Page/about.html
Labels: good first issue, gssoc
